<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-betting_fields for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-betting_fields
 * @see BF_Plugin::add_shortcode_help_tab()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p><?php _e( 'Níže jsou informace o jednotlivých <i>shortcode</i>, které plugin <b>Napojení na XML feedy sázkových kanceláří</b> poskytuje:', BF_SLUG ) ?></p>

<p style="color: #f30;"><?php _e( '<code>XXX</code> Doplnit!', BF_SLUG ) ?></p>

<!--
<p><?php _e( '', BF_SLUG ) ?></p>
-->
