<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-betting_fields for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-betting_fields
 * @see BF_Plugin::add_widget_help_tab()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p><?php _e( 'Níže jsou informace o jednotlivých <i>widgetech</i>, které plugin <b>Napojení na XML feedy sázkových kanceláří</b> poskytuje:', BF_SLUG ) ?></p>

<ul>
    <li><b>Výsledková tabulka PM</b> - widget s výsledkovou listinou soutěže <b>Premiere League</b>. Výsledky jsou přebírány ze serveru <a href="https://premierleague.cz/tabulka/" target="_blank">https://premierleague.cz/tabulka/</a>.</li>
</ul>
<p style="color: #f30;"><?php _e( '<code>XXX</code> Doplnit!', BF_SLUG ) ?></p>

<!--
<p><?php _e( '', BF_SLUG ) ?></p>
-->
