<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-betting_feeds for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-betting_fields
 * @see BF_PMTable_Widget::form()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Normalize instance data
$description = ! empty( $instance['description'] ) ? $instance['description'] : __( 'Premier League 2017/2018', BF_SLUG );
$league      = ! empty( $instance['league'] ) ? $instance['league'] : 'pm2018';
$show_col1   = array_key_exists( 'show_col1', $instance );
$show_col2   = true;
$show_col3   = array_key_exists( 'show_col3', $instance );
$show_col4   = array_key_exists( 'show_col4', $instance );
$show_col5   = array_key_exists( 'show_col5', $instance );
$show_col6   = array_key_exists( 'show_col6', $instance );
$show_col7   = array_key_exists( 'show_col7', $instance );
$show_col8   = array_key_exists( 'show_col8', $instance );
$show_col9   = array_key_exists( 'show_col9', $instance );

?>
<div class="odwpbf-pmtable-widget--form">
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'description' ) ) ?>"><?php esc_attr_e( 'Název:', BF_SLUG ) ?></label> 
        <input class="widefat" id="<?php echo esc_attr( $self->get_field_id( 'description' ) ); ?>" name="<?php echo esc_attr( $self->get_field_name( 'description' ) ); ?>" type="text" value="<?php echo esc_attr( $description ); ?>">
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'description' ) ) ?>"><?php esc_attr_e( 'Soutěž:', BF_SLUG ) ?></label>
        <select class="widefat" id="<?php echo esc_attr( $self->get_field_id( 'league' ) ); ?>" name="<?php echo esc_attr( $self->get_field_name( 'league' ) ); ?>" value="<?php echo esc_attr( $league ); ?>">
            <option value="pm2018"><?php _e( 'Premier League 2017/18', BF_SLUG ) ?></option>
        </select>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col1' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col1' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col1' ) ) ?>" <?php checked( $show_col1 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>pořadí</b>?', BF_SLUG ) ?>
        </label>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col3' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col3' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col3' ) ) ?>" <?php checked( $show_col3 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>počet zápasů</b>?', BF_SLUG ) ?>
        </label>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col4' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col4' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col4' ) ) ?>" <?php checked( $show_col4 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>počet výher</b>?', BF_SLUG ) ?>
        </label>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col5' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col5' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col5' ) ) ?>" <?php checked( $show_col5 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>počet remíz</b>?', BF_SLUG ) ?>
        </label>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col6' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col6' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col6' ) ) ?>" <?php checked( $show_col6 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>počet remíz</b>?', BF_SLUG ) ?>
        </label>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col7' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col7' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col7' ) ) ?>" <?php checked( $show_col7 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>vstřelené góly</b>?', BF_SLUG ) ?>
        </label>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col8' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col8' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col8' ) ) ?>" <?php checked( $show_col8 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>obdržené góly</b>?', BF_SLUG ) ?>
        </label>
    </p>
    <p>
        <label for="<?php echo esc_attr( $self->get_field_id( 'show_col9' ) ) ?>">
            <input type="checkbox" id="<?php echo esc_attr( $self->get_field_id( 'show_col9' ) ) ?>" name="<?php echo esc_attr( $self->get_field_name( 'show_col9' ) ) ?>" <?php checked( $show_col9 ) ?>>
            <?php _e( 'Zobrazit sloupec <b>body</b>?', BF_SLUG ) ?>
        </label>
    </p>
</div>
