<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-betting_feeds for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-betting_fields
 * @see BF_PMTable_Widget::widget()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

if( ! class_exists( 'BF_PMTable_DataSource' ) ) {
    include_once( BF_PATH . 'src/BF_PMTable_DataSource.php' );
}


echo $args['before_widget'];
?>
<div class="odwpbf-pmtable-widget">
    <?php if( ! empty( $instance['title'] ) ) : 
        echo $args['before_title'] . apply_filters( 'widget_title', $instance['title'] ) . $args['after_title'];
    endif; ?>
    <div class="odwpbf-pmtable">
        <div class="odwpbf-pmtable--row odwpbf-pmtable--head">
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col1">P</span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col2">Tým</span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col3">Z</span>
            <!-- celkem [ -->
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col4">V</span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col5">R</span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col6">P</span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col7">G+</span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col8">G-</span>
            <!-- ] -->
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col9">B</span>
        </div>
        <?php 
        $pmtable_data = BF_PMTable_DataSource::get_data();

        if( count( $pmtable_data ) > 0 ) :
            foreach( $pmtable_data as $data ) :

        ?><div class="odwpbf-pmtable--row">
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col1"><?php echo $data['poradi'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col2"><?php echo $data['tym'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col3"><?php echo $data['zapasy'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col4"><?php echo $data['vyhry'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col5"><?php echo $data['remizy'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col6"><?php echo $data['prohry'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col7"><?php echo $data['goly_v'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col8"><?php echo $data['goly_o'] ?></span>
            <span class="odwpbf-pmtable--col odwpbf-pmtable--col9"><?php echo $data['body'] ?></span>
        </div>
        <?php
            endforeach;
        else :
        ?>
        <div class="odwpbf-pmtable--row">
            <p><?php _e( 'Žádná data.', BF_SLUG ) ?></p>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php
echo $args['after_widget'];
?>
