<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-betting_feeds for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-betting_fields
 * @see BF_PMTable_Widget::form()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p class="odwpbf-pmtable-widget no-options-widget"><?php _e( '<code>XXX</code> Dokončit formulář widgetu <code>BF_PMTable_Widget</code>!', BF_SLUG ) ?></p>
